version: '2'
services:
  app:
    image: calendar990
    build:
      context: ./src
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:80"
    volumes:
        - ./src:/usr/src
    command: python -m http.server --bind 0.0.0.0 80

  app-node:
    image: calendar990-node
    build:
      context: ./src
      dockerfile: Dockerfile.node
    volumes:
        - ./src:/usr/src
